import { createServerSupabase } from '@/lib/supabase/server';
import { format } from 'date-fns';
import Link from 'next/link';
import styles from './page.module.css';

export default async function ClientReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createServerSupabase();

  // RLS ensures clients can only see published reports for their client
  const { data: report } = await supabase
    .from('reports')
    .select('id, title, period_start, period_end, ai_enhanced_html, published_at, created_at')
    .eq('id', id)
    .eq('is_published', true)
    .single();

  if (!report || !report.ai_enhanced_html) {
    return <div className={styles.notFound}>Report not found.</div>;
  }

  return (
    <>
      <Link href="/dashboard" className={styles.backLink}>
        ← Back to Reports
      </Link>

      <div className={styles.header}>
        <h1 className={styles.heading}>{report.title}</h1>
        <div className={styles.meta}>
          {report.period_start && report.period_end && (
            <>
              <span>
                {format(new Date(report.period_start), 'MMMM yyyy')} — {format(new Date(report.period_end), 'MMMM yyyy')}
              </span>
              <span className={styles.metaDot} />
            </>
          )}
          <span>
            Published {format(new Date(report.published_at || report.created_at), 'dd MMMM yyyy')}
          </span>
        </div>
      </div>

      <div
        className={styles.reportContent}
        dangerouslySetInnerHTML={{ __html: report.ai_enhanced_html }}
      />

      <div className={styles.footer}>
        Report generated by Shtudio — shtudio.com.au
      </div>
    </>
  );
}
